# Generated by Django 6.0.1 on 2026-01-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_userprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(default='enter employee id', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa_type',
            field=models.CharField(choices=[('Packer', 'Packer'), ('Security', 'Security'), ('Manager', 'Manager')], default='Packer', max_length=100),
        ),
    ]
