# Generated by Django 6.0.1 on 2026-01-22 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_userprofile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='salaryrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='employee_id',
            field=models.CharField(default='enter employee id', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Employee Name', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visa_type',
            field=models.CharField(choices=[('Packer', 'Packer'), ('Security', 'Security'), ('Telecommunication Assistant', 'Telecommunication Assistant')], default='Packer', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
