# Generated by Django 6.0.1 on 2026-01-28 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_remove_attendancerecord_user_remove_payroll_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.DeleteModel(
            name='SalaryRecord',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='net_salary',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='payroll',
            name='employee_id',
            field=models.CharField(default='enter employee id', max_length=20),
        ),
        migrations.AddField(
            model_name='payroll',
            name='name',
            field=models.CharField(default='Employee Name', max_length=100),
        ),
        migrations.AddField(
            model_name='payroll',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
    ]
