# Generated by Django 6.0.1 on 2026-01-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryrecord',
            name='employee_id',
            field=models.CharField(default='enter employee id', max_length=20),
        ),
    ]
