# Generated by Django 6.0.1 on 2026-01-28 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(choices=[('Warehouse Helpers', 'Warehouse Helpers'), ('Security Guard', 'Security Guard')])),
                ('visa_category', models.CharField(choices=[('Packers', 'Packers'), ('Security', 'Security'), ('Team', 'Team')])),
                ('passport_no', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name', 'employee_id', 'visa_category', 'passport_no')},
            },
        ),
    ]
