# Generated by Django 6.0.1 on 2026-01-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_employee_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('name', 'department', 'employee_id', 'visa_category', 'passport_no')},
        ),
    ]
