# Generated by Django 6.0.1 on 2026-01-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absenet'), ('On Leave', 'On Leave')], max_length=10),
        ),
    ]
